"""empty message

Revision ID: 571dd5b918e5
Revises: 391e0f0b62a5
Create Date: 2020-08-12 03:42:50.930340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571dd5b918e5'
down_revision = '391e0f0b62a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###
